postgresql:
    image: postgres
    container_name: postgresql
    labels: 
        - "queue_tests"
    ports: 
        - "5432:5432"
    expose:
        - "5432"
    environment:
        - POSTGRES_PASSWORD=supersecret
        - POSTGRES_DB=queue
        - POSTGRES_USER=queue